name: VSCode Extension CI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [10.16]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      working-directory: common
    - run: npm run compile --if-present
      working-directory: client
    - name: Package extension
      if: success() && github.ref == 'refs/heads/master'
      run: | 
        npm install -g vsce
        vsce package
      working-directory: client
      # See https://github.com/keesschollaart81/vscode-home-assistant/blob/master/.github/workflows/github-actions-vscode-extension.yml
      env:
        CI: true
